version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_Str0ng_P@ssw0rd!
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
